name: CI2

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          if [ "${{ github.repository }}" != "rebhorley/tmp-actions" ]; then
            exit 1
          fi
